In [4]:
import numpy as np
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
np.einsum('ii', a)

60

In [13]:
np.einsum(a, [0,0])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
np.einsum('ii->i', a)

array([ 0,  6, 12, 18, 24])

In [15]:
np.einsum('ij->i', a)

array([ 10,  35,  60,  85, 110])

In [17]:
np.einsum('ji', a)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [19]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [20]:
np.einsum('i,i', b, b)

30

In [22]:
np.einsum(a, [0,1])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b = np.ones(5)
np.einsum(a, [0,1], b, [1]) ## sum of the inner product of every row of a times b

array([ 10.,  35.,  60.,  85., 110.])

In [25]:
np.einsum(a, [1,0], b, [1]) ## sum of the inner product of every col of a times b

array([50., 55., 60., 65., 70.])

In [37]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [38]:
b * b

array([ 0,  1,  4,  9, 16])

In [27]:
f = np.arange(2)+1 
f

array([1, 2])

In [30]:
np.einsum(f, [0], b, [1])  ## outer product

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

In [31]:
np.einsum(f, [0], b, [1], [1])  ## outer product, summed into axis 1

array([3., 3., 3., 3., 3.])

In [32]:
np.einsum(f, [0], b, [1], [0])  ## outer product, summed into axis 1

array([ 5., 10.])

In [ ]:
np.einsum(f, [0], b, [1], [1])  ## outer product

In [39]:
a = np.arange(60.).reshape(3,4,5)
a

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]],

       [[40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59.]]])

In [40]:
b = np.arange(24.).reshape(4,3,2)
b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

In [41]:
np.einsum(a, [0,1,2], b, [1,0,3], [2,3])

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [46]:
np.einsum(a, [0,1,2], b, [1,0,3], [2,3])

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [48]:
p = np.arange(24.).reshape(2,3,4)
b = np.arange(3)
c = np.arange(4)

In [49]:
einsum_args = [p, [0,1,2], b, [1], c, [2]]
np.einsum(*einsum_args)

array([162., 378.])

In [52]:
b = np.arange(3)
c = np.arange(3) + 1
np.einsum(b, [0], c, [1])

array([[0, 0, 0],
       [1, 2, 3],
       [2, 4, 6]])

In [57]:
p = np.arange(6).reshape(2,3)
p

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
np.einsum(p, [0,1], [0,1], [0], [0,1])

array([[0, 0, 0],
       [3, 4, 5]])

In [62]:
p[1,2]

5

In [54]:
p

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
p[:,1] = 0
p

array([[0, 0, 2],
       [3, 0, 5]])

In [ ]:
p.shape